# SPDX-License-Identifier: GPL-2.0
# Enables support for device-tree overlays
dtb-$(CONFIG_SOC_NUCLEI) += nuclei-ux600-sim.dtb
dtb-$(CONFIG_SOC_NUCLEI) += nuclei-ux600.dtb
dtb-$(CONFIG_SOC_NUCLEI) += nuclei-ux600fd-entire.dtb
dtb-$(CONFIG_SOC_NUCLEI) += nuclei-ux600fd-ramfs-jffs2.dtb
dtb-$(CONFIG_SOC_NUCLEI) += nuclei-ux600fd-sim.dtb
dtb-$(CONFIG_SOC_NUCLEI) += nuclei-ux600fd.dtb


